<?php

namespace AppBundle\Repository;

/**
 * MotCleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotCleRepository extends \Doctrine\ORM\EntityRepository
{
}
